# Basic Multi-Channel Model Configuration
defaults:
  - base_config

model:
  type: "basic_multi_channel"
  variant: "standard"
  
  # Architecture
  input_channels: 4  # RGB + L (brightness)
  hidden_channels: [64, 128, 256]
  num_classes: 10
  
  # Multi-channel processing
  channel_groups:
    - [0, 1, 2]  # RGB channels
    - [3]        # Brightness channel
  
  # Integration method
  integration:
    method: "channel_concat"
    fusion_layer: "conv1x1"
    
training:
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 1e-4
